const db = require('../db');
const {Model, DataTypes} = require('sequelize');

class Recipe extends Model {
  // add methods here
}

Recipe.init(
  {
    recipeId: DataTypes.INTEGER,
    //Photos are generated by `https://spoonacular.com/recipeImages/${recipeId}-312x231.jpg`
    name: DataTypes.STRING,
  },
  {
    sequelize: db,
    timestamps: false,
  }
);

module.exports = Recipe;
