const db = require('../db');
const {Model, DataTypes} = require('sequelize');

class Review extends Model {
  // add methods here
}

Review.init(
  {
    userName: DataTypes.STRING,
    //Photos are generated by `https://spoonacular.com/recipeImages/${recipeId}-312x231.jpg`
    review: DataTypes.STRING,
  },
  {
    sequelize: db,
    timestamps: false,
  }
);

module.exports = Review;